### PR TITLE
feat: remove :before and :after for nested Text components

### PR DESCRIPTION
**Pull request by Mhoog**
## Issue
When nesting `<Text />` elements, it would always render the nested component on a new line, including spacing set on the `<Text />` element. This is usually not what you want when you nest `<Text />` elements, as the most common cases are with using inline HTML elements such as `span`, `strong`, `em`, etc.

### For code
```tsx
<Text>This is text, <Text as="strong">and more text</Text></Text>
```

### Before
image

### After
image

### CODE REVIEW

**Comment by andoulla** [comment]
Does this break the capsize functionality?

**Comment by hollg** [comment]
Just for my own understanding, is the benefit of _not_ doing `<Text>This is text, <strong>and more text</strong></Text>` just ensuring that we're using the interfaces provided by this library, or is there some functional benefit too?

**Comment by Mhoog** [comment]
> Does this break the capsize functionality?

@andoulla No, the parent element still has the capsize functionality:
image

**Comment by Mhoog** [comment]
> Just for my own understanding, is the benefit of _not_ doing `<Text>This is text, \<strong\>and more text\</strong\></Text>` just ensuring that we're using the interfaces provided by this library, or is there some functional benefit too?

@hollg, correct. The main benefit of using the `Text` component instead of `<strong />` is that it is then easier to style the inner text. If you'd want to style the `<strong>`, you'd first have to create a `const StyledStrong = styled('strong')`.

**Review by hollg — APPROVED** [review]

**Comment by hollg** [comment]
> > Just for my own understanding, is the benefit of _not_ doing `<Text>This is text, \<strong\>and more text\</strong\></Text>` just ensuring that we're using the interfaces provided by this library, or is there some functional benefit too?
> 
> @hollg, correct. The main benefit of using the `Text` component instead of `<strong />` is that it is then easier to style the inner text. If you'd want to style the `\<strong\>`, you'd first have to create a `const StyledStrong = styled('strong')`.

Makes sense to me, thanks!

**Review by andoulla — APPROVED** [review]

**Pull request merged**
